[package]
name = "tiny-regex"
version = "0.1.0"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
dynasmrt = "1.1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false
