[package]
name = "tiny-regex"
version = "0.1.0"
edition = "2021"
authors = ["Kaede Fujisaki <kaede@hexe.net>"]
license = "AGPL-3.0-or-later"

[dependencies]
dynasmrt = "1.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false
